apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mt-spring-hpa
  namespace: mt-spring-nms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mt-spring-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60